---
- name: Add puppet apt repository key
  ansible.builtin.get_url:
    url: http://apt.puppet.com/keyring.gpg
    dest: /etc/apt/trusted.gpg.d/puppet.asc
    mode: '0644'
    force: true
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: Add puppet repository
  apt_repository:
    repo: deb http://apt.puppet.com {{ ansible_distribution_release }} puppet7
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: run apt-get update
  apt: update_cache=yes cache_valid_time=86400
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: install some needed packages
  apt: name={{ role_vim.install.apt }} state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: install some needed packages with pip
  pip: name={{ role_vim.install.mac_pip }} extra_args='--user'
  when: ansible_distribution == 'MacOSX'

- name: tap with homebrew
  homebrew_tap: name={{ role_vim.repo.homebrew }} state=present
  when: ansible_distribution == 'MacOSX'

- name: install some needed packages with homebrew
  homebrew: name={{ role_vim.install.homebrew }} state=present
  when: ansible_distribution == 'MacOSX'

- name: cleanup users .vimrc
  file:
    path: "{{ ansible_user_dir }}/.vimrc"
    state: absent
  when: cleanup | default(False)

- name: cleanup users .viminfo
  file:
    path: "{{ ansible_user_dir }}/.viminfo"
    state: absent
  when: cleanup | default(False)

- name: cleanup permissions of .vim directory
  file:
    path: "{{ ansible_user_dir }}/.vim"
    state: directory
    recurse: yes
    mode: 0755
  when: cleanup | default(False)

- name: cleanup users .vim
  file:
    path: "{{ ansible_user_dir }}/.vim"
    state: absent
  when: cleanup | default(False)

- name: cleanup users neovim folder
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    state: absent
  when: cleanup | default(False)

- name: create dir for vim pathogen
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/autoload/"
    state: directory

- name: Install vim pathogen
  get_url:
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_user_dir }}/.config/nvim//autoload/pathogen.vim"

- name: Install vim modules
  git:
    repo: "{{ item.value }}"
    dest: "{{ ansible_user_dir }}/.config/nvim/bundle/{{ item.key }}"
    clone: yes
    update: yes
    depth: 1
    recursive: true
    accept_hostkey: yes
  with_dict: "{{ role_vim.vim.module }}"
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in repository' in repo_clone.msg

- name: compile vim autocomplete
  shell: |
    git config --global url."https://".insteadOf git:// # Prevent any connection refused errors
    python3 install.py --all
    git config --global --unset-all url.https://.insteadof
  args:
    chdir: "{{ ansible_user_dir }}/.config/nvim/bundle/YouCompleteMe"
    creates: "{{ ansible_user_dir }}/.config/nvim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so"
    executable: /bin/bash

- name: compile vim command-t
  shell: |
    git config --global url."https://".insteadOf git:// # Prevent any connection refused errors
    make
    git config --global --unset-all url.https://.insteadof
  args:
    chdir: "{{ ansible_user_dir }}/.config/nvim/bundle/command-t/lua/wincent/commandt/lib/"
    creates: "{{ ansible_user_dir }}/.config/nvim/bundle/command-t/lua/wincent/commandt/lib/commandt.so"
    executable: /bin/bash

- name: generate templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
  with_items: "{{ role_vim.environment.home.templates }}"

- name: generate neovim config
  template:
    src: vimrc.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600

- name: Update alternatives
  alternatives:
    name: vi
    path: /usr/bin/nvim
  become: true
  tags:
    - become
