---
- name: run apt-get update
  apt: update_cache=yes cache_valid_time=86400
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: ensures font dir exists
  file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory

- name: install fonts
  unarchive:
    src: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
    dest: "{{ ansible_user_dir }}/.local/share/fonts/"
    remote_src: yes

- name: Download Neovim Package
  get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    dest: /usr/local/bin/nvim.appimage
    mode: '0755'
    force: true
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: install some needed packages
  apt: name={{ role_vim.install.apt }} state=present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - become

- name: install some mac specific packages with pip
  pip: name={{ role_vim.install.mac_pip }} extra_args='--user'
  when: ansible_distribution == 'MacOSX'

- name: install packages with gem
  gem: name={{ item }} state=present
  with_items:
    - "{{ role_vim.install.gem }}"

- name: tap with homebrew
  homebrew_tap: name={{ role_vim.repo.homebrew }} state=present
  when: ansible_distribution == 'MacOSX'

- name: install some needed packages with homebrew
  homebrew: name={{ role_vim.install.homebrew }} state=present
  when: ansible_distribution == 'MacOSX'

- name: ensures config dir exists
  file:
    path: "{{ ansible_user_dir }}/.config/nvim/autoload"
    state: directory

- name: Install neovim Plugin Manager plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/autoload/plug.vim"

- name: generate templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
  with_items: "{{ role_vim.environment.home.templates }}"

- name: generate neovim config
  template:
    src: init.vim.j2
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600

- name: Update alternatives
  alternatives:
    name: vi
    path: /usr/local/bin/nvim.appimage
  become: true
  tags:
    - become
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install neovim Plugins
  shell: /usr/local/bin/nvim.appimage --headless -c 'PlugInstall --sync' -c qa
  args:
    creates: "{{ ansible_user_dir }}/.config/nvim/plugins"
    executable: /bin/bash

- name: Update neovim Plugins
  shell: /usr/local/bin/nvim.appimage --headless -c 'PlugUpdate --sync' -c qa && /usr/local/bin/nvim.appimage --headless -c 'PlugClean --sync' -c qa
  when: update | default(False)

