- name: run apt-get update
  apt: update_cache=yes cache_valid_time=86400
  become: true

- name: install some needed packages
  apt: name={{item}} state=present
  with_items: 
    - "{{ role_vim.install.apt }}"
  become: true

- name: create dir for vim pathogen
  file:
    path: "{{ ansible_user_dir }}/.vim/autoload/"
    state: directory

- name: Install vim pathogen
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload/pathogen.vim"

- name: Install vim modules
  git:
    repo: "{{ item.value }}"
    dest: "{{ ansible_user_dir }}/.vim/bundle/{{ item.key }}"
    clone: yes
    update: yes
    accept_hostkey: yes
  with_dict: "{{ role_vim.vim.module }}"

- name: compile vim autocomplete
  shell: |
    git submodule update --init --recursive 
    ./install.py
  args:
    chdir: "{{ ansible_user_dir }}/.vim/bundle/YouCompleteMe"
    creates: "{{ ansible_user_dir }}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so"
    executable: /bin/bash

- name: generate templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: 0600
  with_items: "{{ role_vim.environment.home.templates }}"
