#!/bin/bash

# SET NVIM_PROJECT_DIR as environment variable to mount your project dir, independent from you current dir

GITDIR=$(git rev-parse --show-toplevel 2> /dev/null)
if [[ $NVIM_PROJECT_DIR ]] ; then
  PRDIR=$NVIM_PROJECT_DIR
else
  PRDIR="${GITDIR:-$PWD}"
fi
PREFIX=/NVIM

volume="nvim-home-$(id -un)"
docker volume inspect "${volume}" > /dev/null 2>&1 || docker volume create "${volume}" > /dev/null

docker run --rm -ti --name "nvim-${$}" \
  -v "${volume}:/home/nvim" \
  -v "${PRDIR}":"${PREFIX}${PRDIR}" \
  -w "${PREFIX}${PWD}" \
  --user "$(id -u):$(id -g)" \
  c8m6/nvim:latest \
  -c "cd ${PREFIX}${PWD}" "${@}"
