#!/bin/bash

GITDIR=$(git rev-parse --show-toplevel 2> /dev/null)
PRDIR="${GITDIR:-$PWD}"
PREFIX=/NVIM

for volume in nvim-share-$(id -un) nvim-state-$(id -un) nvim-config-$(id -un); do
  docker volume inspect "${volume}" > /dev/null 2>&1 || docker volume create "${volume}" /dev/null
done

docker run --rm -ti --name "nvim-${$}" \
  -v "nvim-share:/home/nvim/.local/share/nvim" \
  -v "nvim-state:/home/nvim/.local/state/nvim" \
  -v "nvim-config:/home/nvim/.config/nvim" \
  -v "${PRDIR}":"${PREFIX}${PRDIR}" \
  -w "${PREFIX}${PWD}" \
  --user "$(id -u):$(id -g)" \
  c8m6/nvim:latest \
  -c "cd ${PREFIX}${PWD}" "${@}"
